config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'admin/new/signup'}

  root                  'pages#home'
  get   'about'    =>   'pages#about'
  get   'contact'  =>   'pages#contact'
  get   'news'     =>   'pages#news'
  get   'help'     =>   'pages#help'

  resources :users
  resources :courses do
    resources :coursesemesters do 
      resources :subjects do
        resources :makeassigns do
          resources :submissions
        end
      end
    end
  end
  resources :takes
  resources :sessionenrolls
  resources :coursesessions

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role?
      can :manage, :all if user.role == "admin"
    else
      can :read, :all
      can :update, User do |nothing|
        nothing.user.role == user
      end
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many   :coursesemesters

  validates  :title, presence: true
end

app/models/coursesemester.rb
class Coursesemester < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  has_many   :subjects
  has_many   :makeassigns

  validates  :name,   presence: true
end

app/models/coursesession.rb
class Coursesession < ActiveRecord::Base
  belongs_to  :user
  has_many    :sessionenrolls, dependent: :destroy
  has_many    :makeassigns

  validates   :name,  presence: true
end

app/models/makeassign.rb
class Makeassign < ActiveRecord::Base
  belongs_to :subject
  belongs_to :user
  belongs_to :coursesemester
  belongs_to :coursesession
  has_many   :submissions

  validates  :assign_no,    presence: true
  validates  :start_date,   presence: true
  validates  :end_date,     presence: true
  validates  :body,         presence: true
end

app/models/sessionenroll.rb
class Sessionenroll < ActiveRecord::Base
  belongs_to :coursesession
  belongs_to :user

  validates  :coursesession_id, presence: true
  validates  :user_id,          presence: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :user
  belongs_to :coursesemester
  has_many   :makeassigns

  validates  :name,   presence: true
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :makeassign

  validates  :roll_no,  presence: true
  validates  :sub_body, presence: true
end

app/models/take.rb
class Take < ActiveRecord::Base
  belongs_to  :course
  belongs_to  :user
  
  validates   :course_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  ROLES = %w[admin teacher student]

  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :takes,                dependent: :destroy         
  has_many :courses,              dependent: :destroy         
  has_many :coursesessions,       dependent: :destroy         
  has_many :sessionenrolls,       dependent: :destroy         
  has_many :coursesemesters,      dependent: :destroy         
  has_many :subjects,             dependent: :destroy
  has_many :makeassigns  
  has_many :submissions       
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
  end

  def about
    @user = current_user
    @users = User.all
  end

  def contact
  end

  def news
  end

  def help
  end
end

app/controllers/sessionenrolls_controller.rb
class SessionenrollsController < ApplicationController
  before_action :set_sessionenroll, only: [:show, :edit, :update, :destroy]
  before_filter :unautherized_for_all, only: [:show, :edit, :update, :destroy]
  
  def index
    @sessionenrolls = Sessionenroll.all
    @user = current_user
  end

  def show
  end

  def new
    @sessionenroll = Sessionenroll.new
    @user = current_user
  end

  def edit
  end

  def create
    @user = current_user
    @sessionenroll = current_user.sessionenrolls.build(sessionenroll_params)

    respond_to do |format|
      if @sessionenroll.save
        format.html { redirect_to sessionenrolls_url, notice: 'Sessionenroll was successfully created.' }
        format.json { render :show, status: :created, location: @sessionenroll }
      else
        format.html { render :new }
        format.json { render json: sessionenrolls_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sessionenroll.update(sessionenroll_params)
        format.html { redirect_to sessionenrolls_url, notice: 'Sessionenroll was successfully updated.' }
        format.json { render :show, status: :ok, location: @sessionenroll }
      else
        format.html { render :edit }
        format.json { render json: sessionenrolls_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sessionenroll.destroy
    respond_to do |format|
      format.html { redirect_to sessionenrolls_url, notice: 'Sessionenroll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_sessionenroll
      @sessionenroll = Sessionenroll.find(params[:id])
      @user = current_user
    end

    def sessionenroll_params
      params.require(:sessionenroll).permit(:coursesession_id, :user_id)
    end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :set_take, only: [:show, :edit, :update, :destroy]

  def index
    @takes = Take.all
    @user = current_user
  end

  def show
  end

  def new
    @take = Take.new
    @user = current_user
  end

  def edit
  end

  def create
    @user = current_user
    @take = current_user.takes.build(take_params)

    if @take.save
      flash[:notice] = "Course added successfully."
      redirect_to takes_url
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @take.update(take_params)
        format.html { redirect_to takes_url, notice: 'Course successfully updated.' }
        format.json { render :show, status: :ok, location: @take }
      else
        format.html { render :edit }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # def destroy
  #   @take.destroy
  #   respond_to do |format|
  #     format.html { redirect_to takes_url, notice: 'Course successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

    def set_take
      @take = Take.find(params[:id])
      @user = current_user
    end

    def take_params
      params.require(:take).permit(:course_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
    @user = User.find_by(params[:id])
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    # @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/makeassigns_helper.rb
module MakeassignsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessionenrolls_helper.rb
module SessionenrollsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sessionenrolls/_form.html.erb
<%= form_for(@sessionenroll) do |f| %>
  <% if @sessionenroll.errors.any? %>
    <div class="alert alert-danger">
      <h3><%= pluralize(@sessionenroll.errors.count, "error") %> prohibited this sessionenroll from being saved:</h3>

      <ul>
      <% @sessionenroll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.collection_select :coursesession_id, Coursesession.all, :id, :name, prompt: true %>
<br><br>
    <%= f.submit "Enroll", class: "btn btn-primary" %>
    <%= link_to 'Back', sessionenrolls_path, class: "btn btn-default" %>
<% end %>

app/views/sessionenrolls/edit.html.erb
<h1>Editing Sessionenroll</h1>

<%= render 'form' %>

<%= link_to 'Show', @sessionenroll %> |
<%= link_to 'Back', sessionenrolls_path %>

app/views/sessionenrolls/index.html.erb
<h2>Listing Session Enrollments</h2>

<table class="table">
  <thead>
    <tr>
      <th>Session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.sessionenrolls.each do |sessionenroll| %>
      <tr>
        <td><%= sessionenroll.coursesession.name %></td>
        <td>
        <% if @user.role == "admin" %>
        <%= link_to 'Show', sessionenroll, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_sessionenroll_path(sessionenroll), class: "btn btn-success" %>
        <%= link_to 'Destroy', sessionenroll, method: :delete, data: { confirm: 'Are you sure?' },
                                                                          class: "btn btn-danger" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @user.sessionenrolls.exists? %>
  <% if @user.role == "teacher" %>
    <%= link_to 'New Enrollment', new_sessionenroll_path, class: "btn btn-default" %>
  <% end %>
<% else %>
  <%= link_to 'New Enrollment', new_sessionenroll_path, class: "btn btn-default" %>
<% end %>

app/views/sessionenrolls/new.html.erb
<h2>New Session Enrollment</h2>
<br>
<%= render 'form' %>

app/views/sessionenrolls/show.html.erb
<p>
  <strong>Semester Name:</strong>
  <%= @sessionenrolls.name %>
</p>
<p>
  <strong>Program Name:</strong>
  <%= @coursesemester.course.title %>
</p>