config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'admin/new/signup'}

  root                  'pages#home'
  get   'about'    =>   'pages#about'
  get   'contact'  =>   'pages#contact'
  get   'news'     =>   'pages#news'
  get   'help'     =>   'pages#help'

  resources :users
  resources :courses do
    resources :coursesemesters do 
      resources :subjects do
        resources :makeassigns do
          resources :submissions
        end
      end
    end
  end
  resources :takes
  resources :sessionenrolls
  resources :coursesessions

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role?
      can :manage, :all if user.role == "admin"
    else
      can :read, :all
      can :update, User do |nothing|
        nothing.user.role == user
      end
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many   :coursesemesters

  validates  :title, presence: true
end

app/models/coursesemester.rb
class Coursesemester < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  has_many   :subjects
  has_many   :makeassigns

  validates  :name,   presence: true
end

app/models/coursesession.rb
class Coursesession < ActiveRecord::Base
  belongs_to  :user
  has_many    :sessionenrolls, dependent: :destroy
  has_many    :makeassigns

  validates   :name,  presence: true
end

app/models/makeassign.rb
class Makeassign < ActiveRecord::Base
  belongs_to :subject
  belongs_to :user
  belongs_to :coursesemester
  belongs_to :coursesession
  has_many   :submissions

  validates  :assign_no,    presence: true
  validates  :start_date,   presence: true
  validates  :end_date,     presence: true
  validates  :body,         presence: true
end

app/models/sessionenroll.rb
class Sessionenroll < ActiveRecord::Base
  belongs_to :coursesession
  belongs_to :user

  validates  :coursesession_id, presence: true
  validates  :user_id,          presence: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :user
  belongs_to :coursesemester
  has_many   :makeassigns

  validates  :name,   presence: true
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :makeassign

  validates  :roll_no,  presence: true
  validates  :sub_body, presence: true
end

app/models/take.rb
class Take < ActiveRecord::Base
  belongs_to  :course
  belongs_to  :user
  
  validates   :course_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  ROLES = %w[admin teacher student]

  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :takes,                dependent: :destroy         
  has_many :courses,              dependent: :destroy         
  has_many :coursesessions,       dependent: :destroy         
  has_many :sessionenrolls,       dependent: :destroy         
  has_many :coursesemesters,      dependent: :destroy         
  has_many :subjects,             dependent: :destroy
  has_many :makeassigns  
  has_many :submissions       
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
  end

  def about
    @user = current_user
    @users = User.all
  end

  def contact
  end

  def news
  end

  def help
  end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :set_take, only: [:show, :edit, :update, :destroy]

  def index
    @takes = Take.all
    @user = current_user
  end

  def show
  end

  def new
    @take = Take.new
    @user = current_user
  end

  def edit
  end

  def create
    @user = current_user
    @take = current_user.takes.build(take_params)

    if @take.save
      flash[:notice] = "Course added successfully."
      redirect_to takes_url
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @take.update(take_params)
        format.html { redirect_to takes_url, notice: 'Course successfully updated.' }
        format.json { render :show, status: :ok, location: @take }
      else
        format.html { render :edit }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # def destroy
  #   @take.destroy
  #   respond_to do |format|
  #     format.html { redirect_to takes_url, notice: 'Course successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

    def set_take
      @take = Take.find(params[:id])
      @user = current_user
    end

    def take_params
      params.require(:take).permit(:course_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
    @user = User.find_by(params[:id])
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    # @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/coursesessions_helper.rb
module CoursesessionsHelper
end

app/helpers/makeassigns_helper.rb
module MakeassignsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessionenrolls_helper.rb
module SessionenrollsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_status.html.erb
<table class="table">
  <tbody>
    <% @users.each do |user| %>
    <% if current_user == user %>
      <% if user.role == current_user.role %>
        <tr>
          <% if user.takes.exists? %>
            <% if user.sessionenrolls.exists? %>
            <% else %>
            <% if current_user == user %>
              <td><%= link_to "Enroll", sessionenrolls_path, class: "btn btn-default btn-sm" %></td>
            <% end %>
            <% end %>
            <% if current_user == user %>
            <% if user.role == "teacher" %>
              <td><%= link_to "Other Course", takes_path %> |
              <% if user.sessionenrolls.exists? %>
              <%= link_to "other Enroll", sessionenrolls_path %></td>
              <% end -%>
            <% end -%>
            <% end -%>
          <% else %>
            <% if current_user == user %>
            <td><%= link_to "Select Course", takes_path, class: "btn btn-default btn-sm" %></td>
            <% end %>
          <% end %>
          <td>
          <% if current_user == user %>
            <span class="btn-group btn-group-sm" role="group">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-success" %>
            </span>
          <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <% end -%>
  </tbody>
</table>

app/views/users/index.html.erb
<h2>Users List</h2>
<% if current_user && @user.role == "admin" %>
<table class="table">
  <thead>
    <tr>
      <th>User Name</th>
      <th>User Role</th>
      <th>User Email</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
      <td><%= user.role.titleize %></td>
      <td><%= user.email %></td>
        <% if user.takes.exists? %>
          <td><% user.takes.each do |take| %>
            <%= take.course.title %><br>
          <% end %></td>
        <% else %>
          <td>Not Selected</td>
        <% end %>
      </td>
      <td>
        <span class="btn-group btn-group-sm" role="group">
          <%= link_to "Show", user_path(user), class: "btn btn-primary" %>
        </span>
        <span class="btn-group btn-group-sm" role="group">
          <%= link_to "Edit", edit_user_registration_path, class: "btn btn-success" %>
        </span>
        <span class="btn-group btn-group-sm" role="group">
          <%= link_to "Delete", user, method: :delete, confirm: 'Are You Sure?', class: "btn btn-danger" %>
        </span>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>

<!-- Other then Admin Users -->

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Course</th>
      <th>Session</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <% if current_user == user %>
      <% if user.role == current_user.role %>
        <tr>
          <td><%= link_to user.username, user %></td>
          <td><%= user.email %></td>
          <% if user.takes.exists? %>
            <td>
              <% user.takes.each do |take| %>
                <%= take.course.title %><br />
              <% end %>
            </td>
            <% if user.sessionenrolls.exists? %>
              <td>
                <% user.sessionenrolls.each do |enroll| %>
                  <%= enroll.coursesession.name %><br>
                <% end %>
              </td>
            <% else %>
            <% if current_user == user %>
              <td><%= link_to "Enroll", sessionenrolls_path, class: "btn btn-default btn-sm" %></td>
            <% end %>
            <% end %>
            <% if current_user == user %>
            <% if user.role == "teacher" %>
              <td><%= link_to "Other Course", takes_path %> |
              <% if user.sessionenrolls.exists? %>
              <%= link_to "other Enroll", sessionenrolls_path %></td>
              <% end -%>
            <% end -%>
            <% end -%>
          <% else %>
            <% if current_user == user %>
            <td><%= link_to "Select Course", takes_path, class: "btn btn-default btn-sm" %></td>
            <% end %>
          <% end %>
          <td>
            <span class="btn-group btn-group-sm" role="group">
              <%= link_to "Show", user_path(user), class: "btn btn-primary" %>
            </span>
          <% if current_user == user %>
            <span class="btn-group btn-group-sm" role="group">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-success" %>
            </span>
          <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <% end -%>
  </tbody>
</table>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
  <% if @user.username.present? %>
    <h2><%= @user.username %></h2>
  <% else %>
    Go to profile page update your name.
  <% end -%>
    <table class="table">
      <tr>
        <td><strong>Role:</strong></td>
        <td><%= @user.role.titleize %></td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @user.email %></td>
      </tr>
  </table>
  </div>
  <%= render 'user_status' %>
  <div class="col-md-8">
<!--     <strong>Session:</strong>
    <% @user.sessionenrolls.each do |enroll| %>
    <span class="vdivider">
    <%= enroll.coursesession.name %>
    </span>
    <% end %>
 --> 
  <div class="panel panel-default">
      <% @user.takes.each do |take| %>
    <div class="panel-heading"><strong>Course:</strong><%= take.course.title %></div>
      <% take.course.coursesemesters.each do |semester| %>
    <div class="panel-body">
      <i><%= semester.name %></i>
    </div>
    <% semester.subjects.each do |subject| %>
    <ul class="list-group">
      <li class="list-group-item">
        <%= link_to subject.name, course_coursesemester_subject_path(semester, semester, subject) %>
        <span class="badge"><%= subject.makeassigns.count %></span>
      </li>
    </ul>
      <% end %>
      <% end %>
      <% end %>
  </div>
  </div>
</div>