config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'admin/new/signup'}

  root                  'pages#home'
  get   'about'    =>   'pages#about'
  get   'contact'  =>   'pages#contact'
  get   'news'     =>   'pages#news'
  get   'help'     =>   'pages#help'

  resources :users
  resources :courses do
    resources :coursesemesters do 
      resources :subjects do
        resources :makeassigns do
          resources :submissions
        end
      end
    end
  end
  resources :takes
  resources :sessionenrolls
  resources :coursesessions

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role?
      can :manage, :all if user.role == "admin"
    else
      can :read, :all
      can :update, User do |nothing|
        nothing.user.role == user
      end
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many   :coursesemesters

  validates  :title, presence: true
end

app/models/coursesemester.rb
class Coursesemester < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  has_many   :subjects
  has_many   :makeassigns

  validates  :name,   presence: true
end

app/models/coursesession.rb
class Coursesession < ActiveRecord::Base
  belongs_to  :user
  has_many    :sessionenrolls, dependent: :destroy
  has_many    :makeassigns

  validates   :name,  presence: true
end

app/models/makeassign.rb
class Makeassign < ActiveRecord::Base
  belongs_to :subject
  belongs_to :user
  belongs_to :coursesemester
  belongs_to :coursesession
  has_many   :submissions

  validates  :assign_no,    presence: true
  validates  :start_date,   presence: true
  validates  :end_date,     presence: true
  validates  :body,         presence: true
end

app/models/sessionenroll.rb
class Sessionenroll < ActiveRecord::Base
  belongs_to :coursesession
  belongs_to :user

  validates  :coursesession_id, presence: true
  validates  :user_id,          presence: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :user
  belongs_to :coursesemester
  has_many   :makeassigns

  validates  :name,   presence: true
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :makeassign

  validates  :roll_no,  presence: true
  validates  :sub_body, presence: true
end

app/models/take.rb
class Take < ActiveRecord::Base
  belongs_to  :course
  belongs_to  :user
  
  validates   :course_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  ROLES = %w[admin teacher student]

  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :takes,                dependent: :destroy         
  has_many :courses,              dependent: :destroy         
  has_many :coursesessions,       dependent: :destroy         
  has_many :sessionenrolls,       dependent: :destroy         
  has_many :coursesemesters,      dependent: :destroy         
  has_many :subjects,             dependent: :destroy
  has_many :makeassigns  
  has_many :submissions       
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
  end

  def about
    @user = current_user
    @users = User.all
  end

  def contact
  end

  def news
  end

  def help
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  def index
    @submissions = Submission.all
  end

  def show
      @makeassign = Makeassign.find(params[:id])
      @course = Course.find(params[:course_id])
      @coursesemester = Coursesemester.find(params[:coursesemester_id])
      @subject = Subject.find(params[:subject_id])
      @user = current_user
  end

  def new
    @submission = Submission.new
    @makeassign = Makeassign.find(params[:id])
    @course = Course.find(params[:course_id])
    @coursesemester = Coursesemester.find(params[:coursesemester_id])
    @subject = Subject.find(params[:subject_id])
    @user = current_user
  end

  def edit
  end

  def create
    # @makeassign = Makeassign.find(params[:id])
    @user = current_user
    @course = Course.find(params[:course_id])
    @coursesemester = Coursesemester.find(params[:coursesemester_id])
    @makeassign = Makeassign.find(params[:makeassign_id])
    @submission = @makeassign.submissions.create(submission_params)
    @submission.user = current_user
    respond_to do |format|
      if @submission.save
        format.html { redirect_to :back, notice: 'Assignment Submission was successfully.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_submission
      @submission = Submission.find(params[:id])
      @makeassign = Makeassign.find(params[:makeassign_id])
      @course = Course.find(params[:course_id])
      @coursesemester = Coursesemester.find(params[:coursesemester_id])
      @subject = Subject.find(params[:subject_id])
      @user = current_user
    end

    def submission_params
      params.require(:submission).permit(:user_id, :roll_no, :sub_body, :makeassign_id)
    end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :set_take, only: [:show, :edit, :update, :destroy]

  def index
    @takes = Take.all
    @user = current_user
  end

  def show
  end

  def new
    @take = Take.new
    @user = current_user
  end

  def edit
  end

  def create
    @user = current_user
    @take = current_user.takes.build(take_params)

    if @take.save
      flash[:notice] = "Course added successfully."
      redirect_to takes_url
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @take.update(take_params)
        format.html { redirect_to takes_url, notice: 'Course successfully updated.' }
        format.json { render :show, status: :ok, location: @take }
      else
        format.html { render :edit }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # def destroy
  #   @take.destroy
  #   respond_to do |format|
  #     format.html { redirect_to takes_url, notice: 'Course successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

    def set_take
      @take = Take.find(params[:id])
      @user = current_user
    end

    def take_params
      params.require(:take).permit(:course_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
    @user = User.find_by(params[:id])
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    # @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/coursesessions_helper.rb
module CoursesessionsHelper
end

app/helpers/makeassigns_helper.rb
module MakeassignsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/submissions/_form.html.erb
<script type="text/javascript">
       bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
</script>

<%= form_for([@course, @coursesemester, @subject, @makeassign, @makeassign.submissions.build]) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.number_field :roll_no, class: "form-control", placeholder: "Enter your Roll Number" %>
<br>
    <%= f.hidden_field  :user_id, class: "form-control" %>
<br>
    <%= f.text_area :sub_body, :cols=>"100", :rows=>"5" %>
<br>
    <%= f.submit "Submit Assignment", class: "btn btn-primary" %>
<% end %>

app/views/submissions/_submissions_assignments.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Listing Assignment Submission</div>
  <table class="table">
    <thead>
      <tr>
        <th>Roll no</th>
        <th>Assignment</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @makeassign.submissions.where(user_id: current_user).each do |submission| %>
        <tr>
          <td><%= submission.roll_no %> | <%= submission.user.username %></td>
          <td><%= sanitize submission.sub_body.truncate_words(10), tags: %w(a img), attributes: %w() %></td>
          <td>
          <% if current_user == @user %>
          <%= link_to 'Show', course_coursesemester_subject_makeassign_submission_path(@course, @coursesemester, @subject, @makeassign, submission), class: "btn btn-primary btn-sm" %>
          <% end -%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/submissions/_teacher_assignments_check.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Listing Students Assignment Submission</div>

  <table class="table">
    <thead>
      <tr>
        <th>Roll no</th>
        <th>Assignment</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @makeassign.submissions.each do |submission| %>
        <tr>
          <td><%= submission.roll_no %> | <%= submission.user.username %></td>
          <td><%= sanitize submission.sub_body.truncate_words(10), tags: %w(a img), attributes: %w() %></td>
          <td><%= link_to 'Show', course_coursesemester_subject_makeassign_submission_path(@course, @coursesemester, @subject, @makeassign, submission), class: "btn btn-primary btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Submissions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Roll no</th>
      <th>Sub body</th>
      <th>Makeassign</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.user %></td>
        <td><%= submission.roll_no %></td>
        <td><%= submission.sub_body %></td>
        <td><%= submission.makeassign %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form' %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<div class="well well-sm">
  <strong>Roll no:</strong>
  <%= @submission.roll_no %> | 
  <%= @submission.user.username %>
</div>

<div class="well">
  <strong>Assignment:</strong><hr>
  <%= sanitize @submission.sub_body %>
</div>